### ISSUE TITLE
fix: resolve self (#) references

### ISSUE THREAD

**Issue by Alain1405** [biosustain/potion-node#11]
Potion generated schemas have a JSON reference to themselves.

```
"links":{
    "targetSchema": {
            "$ref": "#"
          }
...
}
```

I extended the potion-node resource with a method that pulls the resource schema:
`Resource.getSchema = Route.GET('/schema');`
but I get this error:
`Uninterpretable or unknown resource URI: #`

As a workaround I now get the schema using ngResource:

```
Resource.getSchema = return $resource(API_URL + 'api/resource/schema').get().$promise;
```

Wouldn't it be useful to have something like the `getSchema` method out of the box in potion-node?
Should potion-node be able to pull/parse the schema?

**Comment by rolandjitsu** [comment]
@lyschoening is there a way to solve this issue from within Flask Potion instead?

**Comment by rolandjitsu** [comment]
@Alain1405 for now, this lib skips resolving `#` references, so that the lib can continue working util a better solution is found.

**Comment by lyschoening** [comment]
@rolandjitsu would it be possible to simply resolve the `"#"` references? The API doesn't use `"#/path"` references, just straightforward `"#"`. So all that would need to be done is adding a `root` parameter to the decoder and returning the root object if the reference is `"#"`. 

See here for the Python implementation: https://github.com/biosustain/potion-client/blob/master/potion_client/converter.py#L128

The only major change required would be that `obj = {}` should be created before the promises are resolved, so that it can be passed as root object to `fromPotionJSON(json, root)` if root is null.

**Comment by rolandjitsu** [comment]
@lyschoening I guess, but I was uncertain if the `#` is different in every child or if it's a reference to the root. If it's just a reference to the root, it should be easy to implement.
