### ISSUE TITLE
fix: resources without $uri cannot be resolved

### ISSUE THREAD

**Issue by rolandjitsu** [biosustain/potion-node#15]
If the flag `include_id` is set to to true in [potion](https://potion.readthedocs.io/en/latest/quickstart.html#meta-class-attributes), potion strips `$uri` from responses and this library is not able to figure out the resource type and it never resolves promises.

@lyschoening is there something we can do about this? Maybe `$uri` should always be there and there should be no option that removes it?

**Comment by lyschoening** [comment]
Ideally the client would look for either $type + $id or $uri

**Comment by galuszkak** [comment]
If I can add my two cents on that @rolandjitsu  @lyschoening . I think this should be more verbose actually. 
`include_id` should only do what it supposed to do which is adding `$id`. If `$uri` is ommited then it should be with something like `exclude_uri` in Meta API. 

That will be much more consistent because maybe someone for some reasone want to have `$id` and `$uri` and doesn't want to manipulate string to get to correct `$id`.

**Comment by lyschoening** [comment]
@galuszkak that is a valid point, but it would be an issue for potion, not potion-client. Do you personally have a use case where you want to include both?

**Comment by rolandjitsu** [comment]
Will be on the next release, but it's available on master.
